In [1]:
import pandas as pd

In [3]:
# Load Final Crime + Socio + Weather Dataset
crime_final = pd.read_csv(
    r"D:\Data_D\TMU\MRP\1.0.Dataset\Crime_Socio_Economic_Weather.csv"
)

# Load Mobility Dataset
mobility = pd.read_csv(
    r"D:\Data_D\TMU\MRP\1.0.Dataset/Mobality/Mobality_Final.csv"
)

In [4]:
crime_final['date'] = pd.to_datetime(crime_final['date']).dt.date
mobility['date'] = pd.to_datetime(mobility['date']).dt.date

In [5]:
print("Crime Dataset Shape :", crime_final.shape)
print("Mobility Dataset Shape :", mobility.shape)

Crime Dataset Shape : (7970658, 33)
Mobility Dataset Shape : (9190, 11)

In [6]:
final_df = pd.merge(
    crime_final,
    mobility,
    on='date',
    how='left'
)

In [7]:
print("Final Dataset Shape :", final_df.shape)

Final Dataset Shape : (7970658, 43)

In [11]:
print(final_df.isnull().sum())

ID                      0
Date                    0
Primary Type            0
Description             0
Location Description    0
Arrest                  0
Domestic                0
Beat                    0
District                0
community_area          0
FBI Code                0
year_x                  0
Latitude                0
Longitude               0
month_x                 0
day_of_week_x           0
hour                    0
is_weekend_x            0
community_name          0
per_capita_income       0
unemployment_rate       0
no_highschool_pct       0
date                    0
TMAX                    0
TMIN                    0
PRCP                    0
SNOW                    0
AWND                    0
temp_avg                0
is_rain                 0
is_snow                 0
temp_category           0
high_wind               0
service_date            0
day_type                0
bus                     0
rail_boardings          0
total_rides             0
year_y                  0
month_y                 0
day                     0
day_of_week_y           0
is_weekend_y            0
dtype: int64

In [9]:
final_df.head()

,ID,Date,Primary Type,Description,Location Description,Arrest,Domestic,Beat,District,community_area,...,service_date,day_type,bus,rail_boardings,total_rides,year_y,month_y,day,day_of_week_y,is_weekend_y
0,6255892,2008-05-17 18:00:00,ROBBERY,ARMED - HANDGUN,RESIDENCE,0,0,511,5.0,49,...,2008-05-17,A,"749,048","350,884","1,099,932",2008,5,17,Saturday,1
1,6272641,2008-05-27 01:00:00,ROBBERY,STRONG ARM - NO WEAPON,STREET,0,1,512,5.0,49,...,2008-05-27,W,"1,026,141","626,634","1,652,775",2008,5,27,Tuesday,0
2,6438609,2008-08-05 22:37:00,ROBBERY,ARMED - HANDGUN,SCHOOL - PUBLIC GROUNDS,0,0,523,5.0,53,...,2008-08-05,W,"997,379","673,384","1,670,763",2008,8,5,Tuesday,0
3,6680276,2008-12-27 20:00:00,BURGLARY,FORCIBLE ENTRY,RESIDENCE - GARAGE,0,0,1622,16.0,11,...,2008-12-27,A,"510,369","254,291","764,660",2008,12,27,Saturday,1
4,13209443,2004-09-17 00:00:00,OFFENSE INVOLVING CHILDREN,AGGRAVATED CRIMINAL SEXUAL ABUSE BY FAMILY MEMBER,RESIDENCE,0,1,935,9.0,61,...,2004-09-17,W,"1,047,045","625,246","1,672,291",2004,9,17,Friday,0

In [10]:
save_path = r"D:\Data_D\TMU\MRP\1.0.Dataset\Crime_Socio_Economic_Weather_Mobility_Final.csv"

final_df.to_csv(save_path, index=False)

In [2]:
csewm = pd.read_csv(r"D:\Data_D\TMU\MRP\1.0.Dataset\Crime_Socio_Economic_Weather_Mobility_Final.csv")

In [4]:
csewm.head(0)

Empty DataFrame
Columns: [ID, Date, Primary Type, Description, Location Description, Arrest, Domestic, Beat, District, community_area, FBI Code, year_x, Latitude, Longitude, month_x, day_of_week_x, hour, is_weekend_x, community_name, per_capita_income, unemployment_rate, no_highschool_pct, date, TMAX, TMIN, PRCP, SNOW, AWND, temp_avg, is_rain, is_snow, temp_category, high_wind, service_date, day_type, bus, rail_boardings, total_rides, year_y, month_y, day, day_of_week_y, is_weekend_y]
Index: []

[0 rows x 43 columns]

In [5]:
csewm.columns

Index(['ID', 'Date', 'Primary Type', 'Description', 'Location Description',
       'Arrest', 'Domestic', 'Beat', 'District', 'community_area', 'FBI Code',
       'year_x', 'Latitude', 'Longitude', 'month_x', 'day_of_week_x', 'hour',
       'is_weekend_x', 'community_name', 'per_capita_income',
       'unemployment_rate', 'no_highschool_pct', 'date', 'TMAX', 'TMIN',
       'PRCP', 'SNOW', 'AWND', 'temp_avg', 'is_rain', 'is_snow',
       'temp_category', 'high_wind', 'service_date', 'day_type', 'bus',
       'rail_boardings', 'total_rides', 'year_y', 'month_y', 'day',
       'day_of_week_y', 'is_weekend_y'],
      dtype='object')