In [1]:
import pandas as pd

In [2]:
weather_df = pd.read_csv(r"D:\Data_D\TMU\MRP\1.0.Dataset\Weather\4301028.csv")

weather_df.head()

,STATION,NAME,DATE,AWND,PRCP,SNOW,SNWD,TMAX,TMIN
0,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",2001-01-01,7.61,0.0,0.0,17.0,24,5
1,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",2001-01-02,8.50,0.0,0.0,15.0,19,5
2,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",2001-01-03,11.41,0.0,0.0,14.0,28,7
3,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",2001-01-04,11.63,0.0,0.0,14.0,30,19
4,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",2001-01-05,13.87,0.0,0.0,13.0,36,21

In [3]:
weather_df = weather_df.rename(columns={'DATE':'date'})
weather_df['date'] = pd.to_datetime(weather_df['date'])
weather_df.head(1)

,STATION,NAME,date,AWND,PRCP,SNOW,SNWD,TMAX,TMIN
0,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",2001-01-01,7.61,0.0,0.0,17.0,24,5

In [4]:
weather_df = weather_df[['date', 'TMAX', 'TMIN', 'PRCP', 'SNOW', 'AWND']]
weather_df.head(1)

        date  TMAX  TMIN  PRCP  SNOW  AWND
0 2001-01-01    24     5   0.0   0.0  7.61

In [5]:
weather_df.shape

(8400, 6)

In [6]:
weather_df[['TMAX', 'TMIN', 'PRCP', 'SNOW', 'AWND']].isnull().sum()

TMAX    0
TMIN    0
PRCP    0
SNOW    0
AWND    0
dtype: int64

In [7]:
weather_df['temp_avg'] = (weather_df['TMAX'] + weather_df['TMIN'])/2
weather_df['is_rain'] = (weather_df['PRCP']>0).astype(int)
weather_df['is_snow'] = (weather_df['SNOW']>0).astype(int)

In [8]:
def temp_category(temp):
    if temp < 32:
        return 'cold'
    elif temp < 60:
        return 'mild'
    else:
        return 'hot'

In [9]:
weather_df['temp_category'] = weather_df['temp_avg'].apply(temp_category)

In [11]:
weather_df['high_wind'] = (weather_df['AWND']>15).astype(int)

In [12]:
weather_df.head(1)

,date,TMAX,TMIN,PRCP,SNOW,AWND,temp_avg,is_rain,is_snow,temp_category,high_wind
0,2001-01-01,24,5,0.0,0.0,7.61,14.5,0,0,cold,0

In [13]:
weather_df.to_csv(r"D:\Data_D\TMU\MRP\1.0.Dataset\Weather\Weather_Final.csv")