In [1]:
import pandas as pd
import numpy as np

In [2]:
cta = pd.read_csv(r"D:\Data_D\TMU\MRP\1.0.Dataset\Mobality\CTA_-_Ridership_-_Daily_Boarding_Totals_20260510.csv")
cta.head()

  service_date day_type      bus rail_boardings total_rides
0   01/01/2001        U  297,192        126,455     423,647
1   01/02/2001        W  780,827        501,952   1,282,779
2   01/03/2001        W  824,923        536,432   1,361,355
3   01/04/2001        W  870,021        550,011   1,420,032
4   01/05/2001        W  890,426        557,917   1,448,343

In [3]:
cta.shape

(9190, 5)

In [4]:
cta.columns

Index(['service_date', 'day_type', 'bus', 'rail_boardings', 'total_rides'], dtype='object')

In [5]:
cta.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9190 entries, 0 to 9189
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   service_date    9190 non-null   object
 1   day_type        9190 non-null   object
 2   bus             9190 non-null   object
 3   rail_boardings  9190 non-null   object
 4   total_rides     9190 non-null   object
dtypes: object(5)
memory usage: 359.1+ KB

In [6]:
cta.isnull().sum()

service_date      0
day_type          0
bus               0
rail_boardings    0
total_rides       0
dtype: int64

In [7]:
cta.dtypes

service_date      object
day_type          object
bus               object
rail_boardings    object
total_rides       object
dtype: object

In [8]:
cta['service_date'] = pd.to_datetime(cta['service_date'])

In [9]:
cta.dtypes

service_date      datetime64[ns]
day_type                  object
bus                       object
rail_boardings            object
total_rides               object
dtype: object

In [10]:
cta['date'] = cta['service_date'].dt.date

In [11]:
cta['year'] = cta['service_date'].dt.year
cta['month'] = cta['service_date'].dt.month
cta['day'] = cta['service_date'].dt.day
cta['day_of_week'] = cta['service_date'].dt.day_name()

In [12]:
cta['is_weekend'] = cta['day_of_week'].isin(['Saturday', 'Sunday']).astype(int)

In [13]:
cta.duplicated().sum()

np.int64(0)

In [14]:
cta.describe()

              service_date         year        month          day   is_weekend
count                 9190  9190.000000  9190.000000  9190.000000  9190.000000
mean   2013-07-31 12:00:00  2013.084113     6.490642    15.726442     0.285637
min    2001-01-01 00:00:00  2001.000000     1.000000     1.000000     0.000000
25%    2007-04-17 06:00:00  2007.000000     3.000000     8.000000     0.000000
50%    2013-07-31 12:00:00  2013.000000     7.000000    16.000000     0.000000
75%    2019-11-14 18:00:00  2019.000000    10.000000    23.000000     1.000000
max    2026-02-28 00:00:00  2026.000000    12.000000    31.000000     1.000000
std                    NaN     7.262711     3.461567     8.799073     0.451742

In [15]:
cta.head()

,service_date,day_type,bus,rail_boardings,total_rides,date,year,month,day,day_of_week,is_weekend
0,2001-01-01,U,"297,192","126,455","423,647",2001-01-01,2001,1,1,Monday,0
1,2001-01-02,W,"780,827","501,952","1,282,779",2001-01-02,2001,1,2,Tuesday,0
2,2001-01-03,W,"824,923","536,432","1,361,355",2001-01-03,2001,1,3,Wednesday,0
3,2001-01-04,W,"870,021","550,011","1,420,032",2001-01-04,2001,1,4,Thursday,0
4,2001-01-05,W,"890,426","557,917","1,448,343",2001-01-05,2001,1,5,Friday,0

In [17]:
cta.to_csv(r"D:\Data_D\TMU\MRP\1.0.Dataset\Mobality\Mobality_Final.csv", index=False)